/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.group.sunset.services;

import Tool.JDBCUtils;
import com.group.sunset.entity.Pedidos;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import org.apache.commons.dbutils.QueryRunner;
import org.apache.commons.dbutils.ResultSetHandler;
import org.apache.commons.dbutils.handlers.BeanListHandler;

/**
 *
 * @author jadut
 */
public class JessmarController {
    
String  GET_LISTA_DE_PEDIDOS = "select * from pedidos order by id desc";
    
public List<Pedidos> getListaPedidos(){
 System.out.println("getListaPedidos");
 Connection dbCon = null;
 List<Pedidos> listapedidos = new ArrayList<Pedidos>();
 
 try{
     
		dbCon = new JDBCUtils().connectDatabase();
                QueryRunner run = new QueryRunner();

                // Use the BeanListHandler implementation to convert all
                // ResultSet rows into a List of Person JavaBeans.
                ResultSetHandler<List<Pedidos>> h = new BeanListHandler<Pedidos>(Pedidos.class);

                // Execute the SQL statement and return the results in a List of
                // Person objects generated by the BeanListHandler.
                listapedidos = run.query(dbCon, GET_LISTA_DE_PEDIDOS, h );

 }catch(Exception e){
                e.printStackTrace();
 }finally{

            if(dbCon!=null){
                 try{
                     dbCon.close();
                 }catch(SQLException sqle){
                 }
             }
            
 }
return listapedidos;
}
    
    
    
    
    
}
